import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LayoutContentProvider from "@/context/LayoutContentContext";
import AuthProvider from "@/context/AuthContext";
import { Suspense } from "react";
import SpotifyPlayerProvider from "@/context/spotify/SpotifyPlayerContext";

const inter = localFont({
  src: "./fonts/InterVariable.ttf",
  variable: "--font-inter",
  weight: "400 700",
});
const roboto = localFont({
  src: "./fonts/RobotoVariable.ttf",
  variable: "--font-roboto",
  weight: "400 700",
});

// const satoshi = localFont({
//   src: "./fonts/SatoshiVariable.ttf",
//   variable: "--font-satoshi",
//   weight: "400 700",
// });

// const sentient = localFont({
//   src: "./fonts/SentientVariable.ttf",
//   variable: "--font-sentient",
//   weight: "400 700",
// });

export const metadata: Metadata = {
  title: "Hobbiverse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto.variable} antialiased`}>
        <Suspense fallback={<div>Loading...</div>}>
          <AuthProvider>
            <SpotifyPlayerProvider>
              <main className="relative w-full h-screen">
                <LayoutContentProvider>{children}</LayoutContentProvider>
              </main>
            </SpotifyPlayerProvider>
          </AuthProvider>
        </Suspense>
      </body>
    </html>
  );
}
